package de.unisaarland.cs.se.selab.ships

const val MIN_VELOCITY_SCOUTING = 10
const val MAX_VELOCITY_SCOUTING = 100
const val MIN_VELOCITY_COORDINATING = 10
const val MAX_VELOCITY_COORDINATING = 50
const val MIN_VELOCITY_COLLECTING = 10
const val MAX_VELOCITY_COLLECTING = 50

const val MIN_ACCELERATION_SCOUTING = 5
const val MAX_ACCELERATION_SCOUTING = 25
const val MIN_ACCELERATION_COORDINATING = 5
const val MAX_ACCELERATION_COORDINATING = 15
const val MIN_ACCELERATION_COLLECTING = 5
const val MAX_ACCELERATION_COLLECTING = 10

const val MIN_FUEL_CAPACITY_SCOUTING = 3000
const val MAX_FUEL_CAPACITY_SCOUTING = 10000
const val MIN_FUEL_CAPACITY_COORDINATING = 3000
const val MAX_FUEL_CAPACITY_COORDINATING = 5000
const val MIN_FUEL_CAPACITY_COLLECTING = 3000
const val MAX_FUEL_CAPACITY_COLLECTING = 5000

const val MIN_FUEL_CONSUMPTION_SCOUTING = 7
const val MAX_FUEL_CONSUMPTION_SCOUTING = 10
const val MIN_FUEL_CONSUMPTION_COORDINATING = 5
const val MAX_FUEL_CONSUMPTION_COORDINATING = 7
const val MIN_FUEL_CONSUMPTION_COLLECTING = 5
const val MAX_FUEL_CONSUMPTION_COLLECTING = 9

const val TEN = 10
