@startuml
participant "sim:Simulator" as sim
participant "c1:Corporation" as c1
participant "task: CollectGarbageTask" as task
participant "s1:ScoutingShip" as s1
participant "s2:CollectingShip" as s2
participant "reward:ContainerReward" as reward
participant "m:Sea" as m
participant "t23:ShallowOcean" as t23
participant "t66:DeepOcean" as t66
participant "t67:DeepOcean" as t67
participant "current:Current" as current
participant "oil:Garbage" as oil
participant "newOil:Garbage" as oil
participant "d: Dijkstra" as d


activate sim

sim -> sim: tick()
activate sim

loop for corporation in {c1}
sim -> c1: getActiveTasks()
activate c1

c1 -> sim: {task}
deactivate c1
end

loop for task in {task}

sim -> task: actUponTick(44)
activate task

task -> task: checkCondition()
activate task

task -> s2: getPos()
activate s2

s2 --> task: t23
deactivate s2

task --> task: true
deactivate task

task -> reward: applyReward(s1)
activate reward

reward -> s1: addCapability (capability)
activate s1

s1 --> reward
deactivate

reward --> task
deactivate reward

task --> sim: true
deactivate task

sim -> c1: removeTask(task)
activate c1

c1 --> sim
deactivate c1
end
deactivate sim

sim --> sim: tick()
activate sim


loop for corporation in {c1}

s -> c1: getOwnedShips()
activate c1

c1 --> s: listOfShips = {s1,s2}
deactivate c1

end

loop for corporation in {c1}

sim -> c1: run(sea, listOfShips)
activate c1

c1 -> c1: moveShips(sea)
activate c1

c1 -> c1: filterCollectingShips()
activate c1

c1 --> c1: {s1,s2}
deactivate c1

c1 -> c1: filterScoutingShips()
activate c1

c1 --> c1: {s1}
deactivate c1

c1 -> c1: getActiveTasks()
activate c1

c1-->c1: {}
deactivate c1

loop for ship in {s1}

c1 -> s1: getTilesWithGarbageInFoV()
activate s1

s1 --> c1: {t66}
deactivate s1
end

loop for tile in {t66}

c1 -> t66: getGarbageByType({OIL})
activate t66

t66 -> c1: {oil}
deactivate t66
end

c1 -> d: execute(t66)
activate d

d --> c1: MapTilesToPath
deactivate d


c1 -> c1: findClosestShip(MapTilesToPath, {s1})
activate c1

c1 --> c1: pathToShip
deactivate c1

c1 -> c1: findClosestHarbor(MapTilesToPath, ownedHarbors)
activate c1

c1 --> c1: pathToHarbor
deactivate c1

loop for scoutingShip in {s1}

c1 -> s1: isFuelSufficient(pathToShip.length + pathToHarbor.length)
activate s1

s1 --> c1: true
deactivate s1

c1 -> s1: move(pathToShip)
activate s1
loop for tile in pathToShip

s1 -> s1: setTile(t66)
activate s1

s1 --> s1:
deactivate s1
end
s1 --> c1
deactivate s1
end


c1 -> c1: findClosestShip(MapTilesToPath, {s1,s2})
activate c1

c1 --> c1: pathToShip
deactivate c1

c1 -> c1: findClosestHarbor(MapTilesToPath, ownedHarbors)
activate c1

c1 --> c1: pathToHarbor
deactivate c1

loop for collectingShip in {s1,s2}

c1 -> s1: isFuelSufficient(pathToShip.length + pathToHarbor.length)
activate s1

s1 --> c1: true
deactivate s1

c1 -> s1: HasGarbageCapacity({oil})
activate s1

s1 --> c1: true
deactivate s1


c1 -> s1: move(pathToShip)
activate s1
loop for tile in pathToShip

s1 -> s1: setTile(t66)
activate s1

s1 --> s1:
deactivate s1
end
s1 --> c1
deactivate s1
end

c1 --> c1
deactivate c1

c1 --> sim:
deactivate c1
end
sim --> sim
deactivate sim
















@enduml