@startuml
participant "sim:Simulator" as s
participant "c1:Corporation" as c1
participant "s1:ScoutingShip" as scouting
participant "s2:CollectingShip" as collecting
participant "m:Map" as m
participant "t66:DeepOcean" as t66
participant "oil:Garbage" as oil
participant "current:Current" as current
participant "t67:Tile" as t67




activate s

s -> s: tick()
activate s

s -> s: runCorporations()
activate s

s -> c1: moveShips()
activate c1
s -> c1: moveShips()

activate scouting

scouting --> c1: {t66}
deactivate scouting


c1 -> scouting: move()
activate scouting

scouting -> scouting:


scouting --> c1
deactivate scouting


c1 --> s

s -> c1: collectGarbage()
c1--> s

s -> c1: refuelShips()
c1--> s

s -> c1: unloadShips()
activate c1

c1 --> s
deactivate c1


s --> s
deactivate s

activate m
s -> m: getTiles()
m --> s : List<Tile>
deactivate m

activate t66
s -> t66: getCurrent()
t66 --> s: curr
deactivate t66

' Here the problem is: Current can drift more than 1 tile, but we call drift(t67,curr)
' without actually computing the destination tile, we just assume it goes there and then
' query getIntensity() and getSpeed() which makes no sense at this point.

activate oil
activate current
s -> oil: drift(t67, curr)
oil -> current: getIntensity()
current --> oil: 1



oil -> current: getSpeed()
current-> oil: 10

oil -> current: getDirection()
current --> oil: D0
deactivate current
oil -> t66: getTileInDirection(D0,1)
activate t66

t66 --> oil: t67
deactivate t66

oil -> oil: canDriftAtOnce(50)
activate oil
oil --> oil: false
deactivate oil


oil -> oil: removeGarbage(OIL,50)
activate oil

oil --> oil
deactivate oil

'need loop to check other tiles if space is not availabel
oil -> t67: isSpaceAvailable(50)
activate t67

t67 --> oil: true

oil -> t67 : isOilPresent()

t67 --> oil: false



oil -> oil: createGarbage(OIL,50)
activate oil

oil --> oil: newOil
deactivate oil

' Here the problem is: Current can drift more than 1 tile, but we call drift(t67,curr)
' without actually computing the destination tile, we just assume it goes there and then
' query getIntensity() and getSpeed() which makes no sense at this point.






oil -> t67: addGarabge(newOil)
t67 --> oil
deactivate t67

oil --> s
deactivate oil


s -> c1: getShips()
c1 --> s: List<Ship>
deactivate c1
activate scouting

scouting -> t66: getCurrent()
activate t66

t66 --> scouting: current
deactivate t66


scouting -> current: getIntensity()
activate current

current --> scouting: 1

scouting -> current: getSpeed()
current --> scouting: 10

scouting -> current: getDirection()
current --> scouting: D0
deactivate current

scouting -> t66: getTileInDirection(D0,1)
activate t66

t66 -> scouting: t67
deactivate t66


scouting --> s
deactivate scouting

s --> s
deactivate s
s -> s: processEvents()
activate s
s --> s
deactivate s

s --> s
deactivate s

@enduml