@startuml
actor User
participant JSONParser as JSONparser

User -> JSONparser: map.json, corporations.json, scenario.json, 0
activate JSONparser
create parser as "m: MapJSONParser"
JSONparser -> parser: parseMap(map.json)

activate parser
loop all tiles in file
parser -> parser: parseNextTile(map.json)
activate parser
parser->parser:validateTile(id, coord, category, harbor, current, direction, speed, intensity)
activate parser
parser -> parser: validateUniqueId(id)
activate parser
parser --> parser: True
deactivate parser
parser -> parser: validateCoordinates(coord)

activate parser
parser --> parser: True
deactivate parser
parser -> parser: validateRequirements(category, harbor, current, direction, speed, intensity)
activate parser
parser --> parser: True
deactivate parser
parser-->parser: True
deactivate parser
create "t:Tiles" as Tiles
parser -> Tiles: Tiles(id, coord, shipTraversable)
activate Tiles

Tiles --> parser: t
deactivate Tiles
parser -> parser: this.tiles.add(t)
activate parser
parser --> parser
deactivate parser
parser -> parser: this.tilesbyId.add(id, t)
activate parser
parser --> parser
deactivate parser
parser -> parser: this.tilesbyCoord.add(coord, t)
activate parser
parser --> parser
deactivate parser
parser --> parser : True
deactivate parser
end
create "m:Map" as map
parser -> map : Map(tiles, tilesbyCoord)
activate map
map --> parser: m
deactivate map
participant Logger as log
parser -> log: logInitializationInfoSuccess(maps.json)
activate log
log --> parser:
deactivate log
parser-->JSONparser: m
deactivate parser
create corparser as "c: CorporartionJSONParser"
JSONparser -> corparser: CorporationJSONParser(m)
activate corparser
corparser --> JSONparser : c
deactivate corparser
JSONparser -> corparser: parseShips(corporations.json)

activate corparser
loop all ships
corparser -> corparser:ValidateShip(id, name, type, corporationId, locationId, maxVelocity, acceleration,  fuelCapacity, fuelConsumption, visibilityRange, garbageType, capacity)
activate corparser
corparser -> corparser: validateShipUniqueId(id)
activate corparser
corparser --> corparser: True
deactivate corparser
corparser -> corparser: validateShipUniqueName(name)
activate corparser
corparser --> corparser: True
deactivate corparser
corparser -> corparser: validateShiplocation(locationId)
activate corparser
corparser -> map: getTilebyId(locationId)
activate map
map --> corparser: tile
deactivate map
corparser -->corparser: True
deactivate corparser
corparser -> corparser: validateShipAttributes(type, maxVelocity, acceleration, fuelCapacity, fuelConsumption, visibilityRange, garbageType, capacity)
activate corparser
corparser --> corparser: True
deactivate corparser
create "s:Ship" as ship
corparser -> ship: Ship(id, name, tile, maxVelocity, acceleration, fuelCapacity, fuelConsumption, visibilityRange, garbageType, capacity)
activate ship
ship -> corparser: s
deactivate ship
corparser -> corparser: this.corporateToShip.get(locationId).add(id)
activate corparser
corparser --> corparser

deactivate corparser
corparser --> corparser
deactivate corparser
end
corparser --> JSONparser
deactivate corparser
JSONparser -> corparser: parseCorporations(corporations.json)
activate corparser
corparser -> corparser: ValidateCorporation(id, name, ships, homeHarbors, garbageTypes)
activate corparser
corparser -> corparser : validateCorporationUniqueId(id)
activate corparser
corparser --> corparser: True
deactivate corparser
corparser-> corparser: validateCorporationUniqueName(name)
activate corparser
corparser --> corparser: True
deactivate corparser
corparser -> corparser: validateHarborTiles()
activate corparser
corparser -> map: getTilebyId(id)
activate map
map --> corparser : t
deactivate map
corparser --> corparser: True
deactivate corparser
corparser -> corparser: validateCorporationShip()
activate corparser
corparser -> corparser : this.mapCorporationToShips.get(id)
activate corparser
corparser --> corparser : List<Int>
deactivate corparser
corparser --> corparser: True
deactivate corparser
corparser -> corparser : validateCorporationGarbageTypes()
activate corparser
corparser --> corparser: True
deactivate corparser
corparser --> corparser : True
deactivate corparser
corparser -> log : logInitializationInfoSuccess(corpartions.json)
activate log
log --> corparser
deactivate log
corparser --> JSONparser
deactivate corparser
create "Sc: ScenarioJSONParser" as scparser
JSONparser -> scparser
activate scparser
scparser -> JSONparser: Sc
deactivate scparser
JSONparser -> scparser : parseGarbage(Scenario.json)
loop all garbages
activate scparser
scparser -> scparser : validateGarbage(id, type, locationID, amount)
activate scparser
scparser -> scparser: validateGarbageUniqueId(id)
activate scparser
scparser --> scparser: True
deactivate scparser
scparser -> scparser: validateGarbageTypeAndAmount(type, amount)
activate scparser
scparser --> scparser: True
deactivate scparser
scparser -> scparser: validateGarbageLocation(locationId)
activate scparser
scparser -> map : getTilebyId(locationId)
activate map
map --> scparser: t
deactivate map
scparser --> scparser: True
deactivate scparser
create "g: Garbage " as garbage
scparser -> garbage: Garbage(id, amount, type, t)
activate garbage
garbage --> scparser: g
deactivate garbage
deactivate scparser
end
scparser --> JSONparser: List<Garbage>
deactivate scparser
JSONparser -> scparser: parseEvents(Scenario.json)
activate scparser
scparser -> scparser: validateEvent(id, type, tick, duration, location, radius, speed, amount, direction, shipID)
activate scparser
scparser -> scparser: validateUniqueId(id)
activate scparser
scparser --> scparser: True
deactivate scparser
scparser -> scparser: validateAttributes(type, duration, location, radius, speed, amount, direction, shipId)
activate scparser
scparser --> scparser: True
deactivate scparser
create "event: Event" as event
scparser -> event: event(id, type, tick, duration, location, radius, speed, amount, direction, shipID)
activate event
event --> scparser: event
deactivate event
scparser --> JSONparser: True








@enduml